(()=>{
  'use strict';
  const C=window.METRO_CONFIG||{}, $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const DAYS=['일','월','화','수','목','금','토'];
  const state={data:{team:[],availability:[],leaves:[],meetings:[],links:[]},view:'today',meetingMonth:new Date(),adminUnlocked:sessionStorage.getItem('metroAdminUnlocked')==='1'};
  const dateKey=d=>{const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`};
  const parseDate=s=>{const m=String(s||'').match(/(20\d{2})-(\d{2})-(\d{2})/);return m?new Date(+m[1],+m[2]-1,+m[3]):null};
  const mins=s=>{const m=String(s||'').match(/(\d{1,2}):(\d{2})/);return m?+m[1]*60 + +m[2]:null};
  const fmtM=n=>`${String(Math.floor(n/60)%24).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;
  const fmtDate=d=>`${d.getMonth()+1}월 ${d.getDate()}일(${DAYS[d.getDay()]})`;
  function showNotice(msg){const n=$('#notice');n.textContent=msg;n.hidden=!msg}
  function api(){if(!C.API_URL)throw new Error('config.js에 Apps Script 웹 앱 주소를 입력해 주세요.');return C.API_URL}
  async function load(quiet=false){
    try{if(!quiet)showNotice('');const res=await fetch(api(),{cache:'no-store'});const json=await res.json();if(!json.ok)throw new Error(json.error||'데이터를 불러오지 못했어요.');state.data={...emptyData(),...json};renderAll()}
    catch(e){showNotice('실제 시트 데이터를 불러오지 못했어요: '+e.message);if(!quiet){state.data=emptyData();renderAll()}}
  }
  function emptyData(){return {team:[],availability:[],leaves:[],meetings:[],links:[]}}
  function activeTeam(){return state.data.team.filter(p=>!['퇴사','나감','장기 OFF','장기OFF'].includes(p.status))}
  function person(name){return state.data.team.find(p=>p.name===name)||{name,team:'',status:'미제출'} }
  function exceptionsFor(name,date){const k=dateKey(date);return state.data.leaves.filter(l=>l.name===name&&k>=l.start&&k<=l.end)}
  function subtractRanges(base,blocked){let out=base.map(x=>({...x}));blocked.forEach(b=>{out=out.flatMap(r=>b.end<=r.start||b.start>=r.end?[r]:[{start:r.start,end:Math.max(r.start,b.start)},{start:Math.min(r.end,b.end),end:r.end}].filter(x=>x.end>x.start))});return out}
  function rangesFor(name,date){
    const day=DAYS[date.getDay()],base=state.data.availability.filter(a=>a.name===name&&a.day===day).flatMap(a=>a.ranges||[]).map(r=>({start:+r.start,end:+r.end})),exceptions=exceptionsFor(name,date);
    const alternate=exceptions.filter(x=>/다른 시간에 일/.test(x.type||''));if(alternate.length)return alternate.at(-1).ranges||[];
    if(exceptions.some(x=>/통째로|하루.*쉬/.test(x.type||'')))return[];
    const blocked=exceptions.filter(x=>/몇 시간|시간만/.test(x.type||'')).flatMap(x=>x.ranges||[]);
    return subtractRanges(base,blocked)
  }
  function isLeave(name,date){return exceptionsFor(name,date).some(x=>/통째로|하루.*쉬/.test(x.type||''))}
  function isAvailable(name,date,start,end){return rangesFor(name,date).some(r=>r.start<=start&&r.end>=end)}
  function meetingOverlap(date,start,end){const k=dateKey(date);return state.data.meetings.some(m=>m.status!=='취소'&&String(m.start).slice(0,10)===k&&mins(String(m.start).slice(11,16))<end&&mins(String(m.end).slice(11,16))>start)}
  function header(title,sub,extra=''){return `<div class="page-head"><div><h1>${title}</h1><p>${sub}</p></div>${extra}</div>`}
  function renderAll(){renderToday();renderWeek();renderMonth();renderMeet();renderTeam();renderLinks();route()}
  function nameTags(list,empty='없음'){return list.length?`<div class="status-tags">${list.map(p=>`<span>${esc(p.name||p)}</span>`).join('')}</div>`:`<div class="status-tags empty-tags">${empty}</div>`}
  function renderToday(){
    const root=$('#today'),now=new Date(),members=activeTeam().filter(p=>rangesFor(p.name,now).length&&!isLeave(p.name,now));
    const nowM=now.getHours()*60+now.getMinutes(),nowPct=nowM/1440*100,onMembers=members.filter(p=>isAvailable(p.name,now,nowM,nowM+1)),longOff=state.data.team.filter(p=>/장기/.test(p.status)),missing=state.data.team.filter(p=>p.status==='미제출');
    root.innerHTML=header('오늘 작업 가능','지금 함께 작업할 수 있는 사람과 오늘의 전체 가능 시간')+`<div class="stats"><div class="card stat"><b>${members.length}</b><span>오늘 작업 가능</span>${nameTags(members)}</div><div class="card stat"><b>${onMembers.length}</b><span>지금 ON</span>${nameTags(onMembers)}</div><div class="card stat"><b>${longOff.length}</b><span>장기 OFF</span>${nameTags(longOff)}</div><div class="card stat"><b>${missing.length}</b><span>스케줄 미제출</span>${nameTags(missing)}</div></div>`+
      `<div class="card scroll"><div class="timeline"><div class="tl-head"><div class="tl-name">이름 / 팀</div><div class="tl-hours"><span class="now-label" style="--now:${nowPct}%" id="clock">${now.toLocaleTimeString('ko-KR',{hour12:false})}</span>${Array.from({length:25},(_,h)=>`<span class="hour" style="left:${h/24*100}%">${String(h).padStart(2,'0')}</span>`).join('')}</div></div>${members.length?members.map(p=>{const on=isAvailable(p.name,now,nowM,nowM+1);return `<div class="tl-row"><div class="tl-name"><strong>${esc(p.name)}</strong>${on?'<span class="on">ON</span>':''}<br><small>${esc(p.team)}</small></div><div class="tl-track"><i class="now-line" style="--now:${nowPct}%"></i>${rangesFor(p.name,now).map(r=>`<span class="bar" style="--l:${r.start/1440*100}%;--w:${(r.end-r.start)/1440*100}%">${fmtM(r.start)}–${fmtM(r.end)}</span>`).join('')}</div></div>`}).join(''):'<p class="empty">오늘 가능한 사람이 없어요.</p>'}</div></div>`;
  }
  function weekDates(){const n=new Date(),sun=new Date(n);sun.setDate(n.getDate()-n.getDay());return Array.from({length:7},(_,i)=>{const d=new Date(sun);d.setDate(sun.getDate()+i);return d})}
  function renderWeek(){const ds=weekDates(),members=activeTeam();$('#week').innerHTML=header('이번 주','이름을 고정하고 요일별 가능 시간을 한눈에 확인합니다')+`<div class="card scroll"><table class="week-grid"><thead><tr><th>이름</th>${ds.map(d=>`<th>${DAYS[d.getDay()]}<br><small>${d.getMonth()+1}/${d.getDate()}</small></th>`).join('')}</tr></thead><tbody>${members.map(p=>`<tr><td><strong>${esc(p.name)}</strong><br><small>${esc(p.team)}</small></td>${ds.map(d=>`<td>${isLeave(p.name,d)?'<span class="pill leave">휴가·일정</span>':rangesFor(p.name,d).length?rangesFor(p.name,d).map(r=>`<span class="pill">${fmtM(r.start)}–${fmtM(r.end)}</span>`).join(''):'<span class="pill off">OFF</span>'}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
  function calendarHtml(year,month,includeMeet=true){const first=new Date(year,month,1).getDay(),last=new Date(year,month+1,0).getDate(),today=dateKey(new Date()),cells=[];for(let i=0;i<first;i++)cells.push('<div class="day blank"></div>');for(let d=1;d<=last;d++){const date=new Date(year,month,d),k=dateKey(date);const leaves=state.data.leaves.filter(l=>k>=l.start&&k<=l.end);const meetings=includeMeet?state.data.meetings.filter(m=>m.status!=='취소'&&String(m.start).slice(0,10)===k):[];cells.push(`<div class="day${k===today?' today':''}"><span class="day-num">${d}</span>${leaves.map(l=>`<span class="event leave">${esc(l.name)}</span>`).join('')}${meetings.map(m=>`<span class="event meeting">${esc(String(m.start).slice(11,16))} ${esc(m.title)}</span>`).join('')}</div>`)}return `<div class="calendar">${DAYS.map(x=>`<span class="dow">${x}</span>`).join('')}${cells.join('')}</div>`}
  function renderMonth(){const n=new Date();$('#month').innerHTML=header('이번 달','휴가·외부 일정과 확정 회의를 함께 확인합니다')+`<div class="card">${calendarHtml(n.getFullYear(),n.getMonth())}</div>`}
  function renderMeet(){
    const root=$('#meet'),members=activeTeam().filter(p=>!/장기/.test(p.status));const n=new Date(),start=dateKey(n),end=dateKey(new Date(n.getFullYear(),n.getMonth(),n.getDate()+14));
    root.innerHTML=header('회의 시간 찾기','참여자를 선택하면 가능한 시간을 계산하고 바로 확정합니다')+`<div class="meet-layout"><div><form id="meetForm" class="card form-card"><div class="form-grid"><div class="field full"><label for="mtTitle">회의 이름</label><input id="mtTitle" required placeholder="예: 스토리팀 정기 회의"></div><div class="field full"><span class="label">참여 인원</span><div class="member-picker">${members.map(p=>`<label class="member-check"><input type="checkbox" name="members" value="${esc(p.name)}">${esc(p.name)}</label>`).join('')||'<span class="empty">팀 명단을 불러오면 표시됩니다.</span>'}</div></div><div class="field"><label for="mtLength">회의 길이(분)</label><input id="mtLength" type="number" min="15" step="5" value="60" required></div><div class="field"><label for="mtStep">후보 간격</label><select id="mtStep"><option value="30">30분</option><option value="15">15분</option><option value="60">1시간</option></select></div><div class="field"><label for="mtFrom">확인 시작일</label><input id="mtFrom" type="date" value="${start}" required></div><div class="field"><label for="mtTo">확인 종료일</label><input id="mtTo" type="date" value="${end}" required></div><div class="field"><label for="mtDayStart">하루 시작 시간</label><input id="mtDayStart" type="time" value="10:00" required></div><div class="field"><label for="mtDayEnd">하루 종료 시간</label><input id="mtDayEnd" type="time" value="24:00" required></div><div class="field full"><label for="mtPlace">회의 링크/장소(선택)</label><input id="mtPlace" placeholder="Discord 채널 또는 회의 링크"></div><button class="primary field full" type="submit">후보 시간 찾기</button></div></form><div id="candidates" class="candidate-list"></div><div id="copyBox"></div></div><div><section class="card calendar-card"><div class="page-head" style="padding:14px 14px 0;margin:0"><div><h2 style="font-size:1.05rem">확정 회의 캘린더</h2><p>${n.getFullYear()}년 ${n.getMonth()+1}월</p></div></div>${calendarHtml(n.getFullYear(),n.getMonth(),true)}</section><div class="confirmed">${state.data.meetings.filter(m=>m.status!=='취소').map(m=>`<article class="confirmed-item"><strong>${esc(m.title)}</strong><br><small>${esc(String(m.start).replace('T',' '))} · ${esc((m.members||[]).join(', '))}</small></article>`).join('')||'<div class="card empty">아직 확정된 회의가 없어요.</div>'}</div></div></div>`;
    $('#meetForm').addEventListener('submit',findCandidates);root.addEventListener('click',e=>{const b=e.target.closest('[data-fix]');if(b)confirmMeeting(JSON.parse(decodeURIComponent(b.dataset.fix)));const c=e.target.closest('#copyNotice');if(c){navigator.clipboard.writeText($('#noticeText').value);c.textContent='복사 완료'}})
  }
  function findCandidates(e){e.preventDefault();const f=e.currentTarget,names=[...f.querySelectorAll('[name="members"]:checked')].map(x=>x.value);if(!names.length)return showNotice('참여자를 한 명 이상 선택해 주세요.');showNotice('');const title=$('#mtTitle').value.trim(),duration=+$('#mtLength').value,step=+$('#mtStep').value,from=parseDate($('#mtFrom').value),to=parseDate($('#mtTo').value),dayStart=mins($('#mtDayStart').value),dayEnd=$('#mtDayEnd').value==='24:00'?1440:mins($('#mtDayEnd').value),place=$('#mtPlace').value.trim(),pending=names.filter(n=>/확인/.test(person(n).status)),scheduled=names.filter(n=>!pending.includes(n)),out=[];for(let d=new Date(from);d<=to;d.setDate(d.getDate()+1)){for(let s=dayStart;s+duration<=dayEnd;s+=step){const available=scheduled.filter(n=>isAvailable(n,d,s,s+duration));if((available.length||!scheduled.length)&&!meetingOverlap(d,s,s+duration))out.push({title,date:dateKey(d),start:fmtM(s),end:fmtM(s+duration),members:names,available,pending,scheduledCount:scheduled.length,place})}}out.sort((a,b)=>b.available.length-a.available.length||(`${a.date}${a.start}`).localeCompare(`${b.date}${b.start}`));$('#candidates').innerHTML=out.length?`<h2 class="section-title">후보 시간 <small>(${out.length}개 중 상위 30개)</small></h2>`+out.slice(0,30).map(x=>{const fixed=x.scheduledCount?x.available.length===x.scheduledCount?'등록 스케줄 기준 전원 가능':`${x.scheduledCount}명 중 ${x.available.length}명 가능`:'등록 스케줄 없음',check=x.pending.length?` · 개별 확인: ${esc(x.pending.join(', '))}`:'';return `<article class="candidate"><div><strong>${esc(fmtDate(parseDate(x.date)))} ${x.start}–${x.end}</strong><small>${fixed}${check}${x.available.length?` · ${esc(x.available.join(', '))}`:''}</small></div><button class="primary" data-fix="${encodeURIComponent(JSON.stringify(x))}" type="button">이 시간 확정</button></article>`}).join(''):'<div class="card empty">선택한 조건에서 가능한 시간이 없어요. 기간이나 시간을 넓혀보세요.</div>'}
  async function confirmMeeting(x){const pass=prompt('회의를 확정할 관리 비밀번호를 입력해 주세요.');if(!pass)return;try{const body={action:'create',pass,meeting:{'회의명':x.title,'시작 일시':`${x.date} ${x.start}`,'종료 일시':`${x.date} ${x.end}`,'참석자':x.members.join(', '),'관련 팀':[...new Set(x.members.map(n=>person(n).team).filter(Boolean))].join(', ')||'전체','회의 링크/장소':x.place,'상태':'확정'}};const res=await fetch(api(),{method:'POST',body:JSON.stringify(body)}),json=await res.json();if(!json.ok)throw new Error(json.error||'저장하지 못했어요.');state.data.meetings=json.meetings||state.data.meetings;const d=parseDate(x.date),notice=`📅 ${x.title} 안내\n\n일시: ${d.getFullYear()}년 ${d.getMonth()+1}월 ${d.getDate()}일(${DAYS[d.getDay()]}) ${x.start}~${x.end}\n참석자: ${x.members.join(', ')}${x.place?`\n회의 링크/장소: ${x.place}`:''}\n\n확인 부탁드립니다!`;renderMeet();renderMonth();$('#copyBox').innerHTML=`<div class="notice-copy"><strong>공지사항</strong><textarea id="noticeText" readonly>${esc(notice)}</textarea><button id="copyNotice" class="primary" type="button">공지문 복사</button></div>`;showNotice('회의가 확정 회의 캘린더에 저장됐어요.')}catch(e){showNotice(e.message)}}
  async function adminRequest(body){const res=await fetch(api(),{method:'POST',body:JSON.stringify(body)}),json=await res.json();if(!json.ok)throw new Error(json.error||'요청을 처리하지 못했어요.');return json}
  function renderTeam(){
    const root=$('#team');
    if(!state.adminUnlocked){
      root.innerHTML=header('팀 명단','관리자만 확인할 수 있습니다')+`<form id="teamUnlock" class="card unlock-card"><h2 class="section-title">관리자 확인</h2><p>관리 비밀번호를 입력하면 팀 상태와 명단을 볼 수 있어요.</p><input id="teamPass" type="password" autocomplete="current-password" required placeholder="관리 비밀번호"><button class="primary" type="submit">팀 명단 열기</button></form>`;
      $('#teamUnlock').addEventListener('submit',async e=>{e.preventDefault();try{await adminRequest({action:'auth',pass:$('#teamPass').value});state.adminUnlocked=true;sessionStorage.setItem('metroAdminUnlocked','1');showNotice('관리자 확인이 완료됐어요.');renderTeam()}catch(err){showNotice(err.message)}});return
    }
    const groups=[['활동 중',p=>!p.status||['활동','활동 중','재직','미제출'].includes(p.status)],['일정별 확인',p=>/확인/.test(p.status)],['장기 OFF',p=>/장기/.test(p.status)],['나간 사람',p=>/퇴사|나감|탈퇴/.test(p.status)]];
    root.innerHTML=header('팀 명단','현재 팀 상태와 일정 확인 방법을 구분해 확인합니다','<button id="lockTeam" class="ghost" type="button">잠그기</button>')+`<div class="team-groups">${groups.map(([name,fn])=>`<section class="card team-group"><h2 class="section-title">${name}</h2>${state.data.team.filter(fn).map(p=>`<div class="person"><strong>${esc(p.name)}</strong><small>${p.status==='미제출'?'<b class="missing">미제출</b> ':''}${esc(p.team)}</small></div>`).join('')||'<p class="empty">해당 인원이 없어요.</p>'}</section>`).join('')}</div>`;
    $('#lockTeam').addEventListener('click',()=>{state.adminUnlocked=false;sessionStorage.removeItem('metroAdminUnlocked');renderTeam()})
  }
  function renderLinks(){
    const root=$('#links'),builtins=[{title:'출근판 관리자 시트',url:C.SHEET_URL},{title:'작업 가능 시간 입력',url:C.WORK_FORM_URL},{title:'휴가·외부 일정 입력',url:C.LEAVE_FORM_URL}],custom=state.data.links||[];
    root.innerHTML=header('링크 허브','팀 운영에 자주 사용하는 링크를 모아두고 직접 추가할 수 있어요')+`<div class="links">${builtins.filter(x=>x.url).map(x=>`<a class="card link-card" href="${esc(x.url)}" target="_blank" rel="noopener"><strong>${esc(x.title)}</strong><span>새 창에서 열기 →</span></a>`).join('')}${custom.map(x=>`<article class="card link-card custom-link"><a href="${esc(x.url)}" target="_blank" rel="noopener"><strong>${esc(x.title)}</strong><span>${x.memo?esc(x.memo):'새 창에서 열기 →'}</span></a><button type="button" class="link-delete" data-link-delete="${esc(x.id)}" aria-label="${esc(x.title)} 삭제">×</button></article>`).join('')}</div><details class="card link-manage"><summary>＋ 링크 추가</summary><form id="linkForm" class="form-grid"><div class="field"><label for="linkTitle">링크 이름</label><input id="linkTitle" required placeholder="예: 디스코드"></div><div class="field"><label for="linkUrl">주소</label><input id="linkUrl" type="url" required placeholder="https://"></div><div class="field full"><label for="linkMemo">설명(선택)</label><input id="linkMemo" placeholder="어떤 링크인지 짧게 적어주세요"></div><div class="field full"><label for="linkPass">관리 비밀번호</label><input id="linkPass" type="password" required autocomplete="current-password"></div><button class="primary field full" type="submit">링크 저장</button></form></details>`;
    $('#linkForm').addEventListener('submit',async e=>{e.preventDefault();try{const json=await adminRequest({action:'link_create',pass:$('#linkPass').value,link:{title:$('#linkTitle').value,url:$('#linkUrl').value,memo:$('#linkMemo').value}});state.data.links=json.links||[];showNotice('링크를 저장했어요.');renderLinks()}catch(err){showNotice(err.message)}});
    root.querySelectorAll('[data-link-delete]').forEach(b=>b.addEventListener('click',async()=>{const pass=prompt('링크를 삭제할 관리 비밀번호를 입력해 주세요.');if(!pass)return;try{const json=await adminRequest({action:'link_delete',pass,id:b.dataset.linkDelete});state.data.links=json.links||[];showNotice('링크를 삭제했어요.');renderLinks()}catch(err){showNotice(err.message)}}))
  }
  function route(){const id=(location.hash||'#today').slice(1);state.view=$('#'+id)?id:'today';document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!==state.view);document.querySelectorAll('#nav a').forEach(a=>a.classList.toggle('active',a.dataset.view===state.view))}
  $('#refreshBtn').addEventListener('click',()=>load(false));window.addEventListener('hashchange',route);$('#todayLabel').textContent=new Date().toLocaleDateString('ko-KR',{year:'numeric',month:'long',day:'numeric',weekday:'short'});setInterval(()=>{const c=$('#clock');if(c)c.textContent=new Date().toLocaleTimeString('ko-KR',{hour12:false})},1000);setInterval(()=>{const tag=document.activeElement?.tagName;if(!document.hidden&&!['INPUT','TEXTAREA','SELECT'].includes(tag))load(true)},60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)load(true)});load();
})();
